Opacity and zoom for android  rebased for capacitor-3
capacitor-community/camera-preview pull request #178
Opened 2021-11-09 04:04 UTC by johnbyrne7

Added opacity control for web and Android.  Suitable for AR type projects.

Also added pinch/zoom for Android.  This works for both toBack options (true, false),

2021-11-09 07:52 UTC, pbowyer commented
Thanks @johnbyrne7, can you please change the target branch to capacitor-3 as it seems GitHub doesn't give me a way to do this in the UI. Thanks!
![image](https://user-images.githubusercontent.com/89852/140883717-9646a781-724d-47b4-9dc4-c8006e85f055.png)

2021-11-22 09:49 UTC, damngamerz commented
@pbowyer Can you merge this and release the new beta? I'm using camera-preview with appflow deployments for development and testing. would be super helpful to have this there, so I can migrate my project to capacitor 3. Thank you.

2021-11-22 09:53 UTC, pbowyer commented
@damngamerz I plan to merge it this week 👍

I don't have permissions to release it though, so we have to wait on someone else to do that.

2021-11-22 09:55 UTC, arielhernandezmusa commented
@pbowyer let me know when you need to release it, I can do it.

2021-11-22 10:14 UTC, pbowyer commented
@arielhernandezmusa Awesome! Could you push out [beta 1](https://github.com/capacitor-community/camera-preview/tree/v2.0.0-beta.1) now please, and later this week I'll finalise beta2 with this and another PR merged?

New Mac should be delivered this week which will make testing _a lot_ quicker 🤩

2021-11-26 08:26 UTC, damngamerz commented
@arielhernandezmusa The changes I need for iOS build are present in beta 1. Can you release this? Would be really helpful. Thanks :smile:

2021-11-26 09:18 UTC, Raphael-Schulz commented
Hey @arielhernandezmusa our team would also need the changes from [beta 1](https://github.com/capacitor-community/camera-preview/tree/v2.0.0-beta.1). Would be awesome if it could be released soon 😃

2021-12-02 09:30 UTC, damngamerz commented
@pbowyer @arielhernandezmusa any updates here?

2021-12-02 13:35 UTC, pbowyer commented
@damngamerz I can't do anything to get it released, sorry.

I haven't finished testing this PR yet; did all features work for you? And which version(s) of Android did you test on?

2021-12-02 14:18 UTC, damngamerz commented
@pbowyer Sorry if my message wasn't clear before. I meant it for the [beta 1](https://github.com/capacitor-community/camera-preview/tree/v2.0.0-beta.1), this PR isn't the priority for me atm. We can take time to merge it.

Though I do need beta 1 as it fixes the versions to 12 in iOS which is a minimum requirement for capacitor 3 bump.

2021-12-02 14:19 UTC, pbowyer requested changes
Thank you for these two additions - they're awesome!

In the same way opacity can be enabled/disabled, can you add a setting to enable/disable zoom? I couldn't see one already present, but do correct me if that's wrong.

2021-12-02 14:19 UTC, pbowyer commented on src/web.ts
> +  async setOpacity(_options CameraOpacityOptions): Promise<any> {
```suggestion
  async setOpacity(_options: CameraOpacityOptions): Promise<any> {
```
Missing colon

2021-12-02 14:19 UTC, pbowyer commented on src/web.ts
> +	   video.style.setProperty("opacity", _options['opacity']);
```suggestion
	   video.style.setProperty("opacity", _options['opacity'].toString());
```

2021-12-02 14:23 UTC, pbowyer commented
> Isn't there somebody in the community who you can reach to get access to npm registry?

@damngamerz I have tried :) Rightfully so they keep tight control over who can publish to NPM. I'll see what I can do - NPM is brand new to me but I'm looking to release my own package(s) to side-step the issue.

2021-12-02 14:59 UTC, pbowyer commented
@damngamerz @Raphael-Schulz  Please try installing this: https://www.npmjs.com/package/@pbowyer/camera-preview

2021-12-16 18:26 UTC, johnbyrne7 commented on src/web.ts
> +  async setOpacity(_options CameraOpacityOptions): Promise<any> {
updated PR

2021-12-16 18:27 UTC, johnbyrne7 commented on src/web.ts
> +	   video.style.setProperty("opacity", _options['opacity']);
updated PR

2021-12-16 18:27 UTC, johnbyrne7 commented on android/src/main/java/com/ahm/capacitor/camera/preview/CameraActivity.java
> +					if (dragEnabled) {
added enableZoom option in definitions.  defaults to false

2021-12-16 20:45 UTC, pbowyer approved these changes
Sorry for the delay, I wasn't notified you'd pushed!

2021-12-16 20:47 UTC, merged